#!/usr/bin/env python3
from argparse import ArgumentParser
import requests
import zlib
import threading
from socket import socket, AF_INET, SOCK_DGRAM
import sqlite3

# parse arguments and store them accordingly
parser = ArgumentParser(
    prog="deployCDN", description="deploy necessary resources to set up a CDN"
)
parser.add_argument("-p", dest="port")
parser.add_argument("-o", dest="origin")
parser.add_argument("-n", dest="name")
parser.add_argument("-u", dest="username")
parser.add_argument("-i", dest="keyfile")

args = parser.parse_args()

if args.port is None:
    raise ValueError("No value for port supplied")
if args.origin is None:
    raise ValueError("No value for origin supplied")

PORT = args.port
ORIGIN = args.origin

connect_db = sqlite3.connect("web_cache.db")
db = connect_db.cursor()
db.execute("CREATE TABLE IF NOT EXISTS CACHE (Path TEXT, Data BLOB);")

# 19920000 20 MB
# 14940000 15 MB


def get_data(path):
    # check if path starts with forward slash
    if len(path) > 0 and path[0] == "/":
        path = path[1:]

    # attempt to get compressed data from the cache db
    db.execute("SELECT Data FROM Cache WHERE Path = :Path", {"Path": path})
    data_or_none = db.fetchone()

    # get data from origin if None or unzip and return the cached data
    if data_or_none == None:
        print(f"inserting {path}")
        url = "http://" + ORIGIN + ":8080/" + path
        url_data = requests.get(url)
        return url_data
    else:
        unzipped_data = zlib.decompress(data_or_none[0])
        return unzipped_data


def serve_client(client_sock: socket, ret_addr):
    req = client_sock.recvfrom(10000)
    # extract path from request
    req_type = req[0].decode("utf-8").split("\r\n")[0]
    req_toks = req_type.split()
    path = ""
    if req_toks[0] == "GET":
        path = req_toks[1]
    response = ""
    if path == "/grading/beacon":
        response = (
            "HTTP/1.1 204 No Content \r\n"
            + "Content-Length: 0\nContent-Type: text/html\n\n"
        )
    else:
        data = get_data(path).decode("utf-8")
        response = (
            "HTTP/1.1 200 OK \r\n"
            + "Content-Length: "
            + str(len(data))
            + "\n"
            + "Content-Type: text/html\n\n"
            + data
        )
    client_sock.send(response)
    client_sock.close()


# create socket to serve data
# set up server socket
sock = socket(AF_INET, SOCK_DGRAM)
sock.connect(("10.0.0.0", 0))
IP = sock.getsockname()[0]
sock.close()
http_sock = socket(AF_INET, SOCK_DGRAM)
http_sock.bind((IP, PORT))
http_sock.listen(1)

while True:
    client_sock, ret_addr = http_sock.accept()
    new_thread = threading.Thread(target=serve_client, args=[client_sock, ret_addr])
    new_thread.start()
